apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mydb
  name: mydb
spec:
  containers:
  - image: mysql:5.7
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: pass
    - name: MYSQL_DATABASE
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: db
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: user
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: user_pass
    name: mydb
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
